### ISSUE TITLE
[rad-auth] Not able to end process when missing RAD_HOME env and no identities available

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-client-tools#24]
CLI ends silently while checking for existing profiles if the `RAD_HOME` env variable isn't set or no identities are available

Eventually we should return some kind of error, that the user should define the env variable, or use as default `~/.radicle`
Atm we go silent, and the user does not know what happened

**Comment by cloudhead** [comment]
Do you know what is causing the panic? I don't have RAD_HOME set and am not getting a panic.

**Comment by sebastinez** [comment]
> Do you know what is causing the panic? I don't have RAD_HOME set and am not getting a panic.

Yeah the panicking was my doing, the CLI ends without information, but with the current PR you are doing it improves.

State with PR #25 when no identities are available and `RAD_HOME` isn't set.
![Screenshot from 2022-01-19 16-55-52](https://user-images.githubusercontent.com/7912302/150167241-b7a2acde-f4c8-46db-84f0-46c56ffcb5dd.png)
 
Eventually we can difference between Error states and show a more meaningful error messages.

Will close this issue for now
