### ISSUE TITLE
[rad-clone] set rad.seed on clone

### ISSUE THREAD

**Issue by mattosborn** [radicle-dev/radicle-client-tools#37]
`rad clone` should set `rad.seed` to the seed chosen/specified

**Comment by cloudhead** [comment]
Ah, you mean locally? That's a good idea.

**Comment by mattosborn** [comment]
Locally yea. A related suggestion is that it might be nice to have a `rad` wrapper to show/update the configured seed. Currently I'm using `git config rad.seed <seed>`

**Comment by cloudhead** [comment]
Fixed in c6ecf26acb050bf16612b26da2f5dd48d46ab90e

I'm considering a wrapper, though it's so minimal that it almost doesn't seem worthwhile.
